package view;

import java.awt.HeadlessException;
import java.util.Enumeration;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import model.Desenvolvedor;
import model.Estagiario;
import model.Gerente;

public class FolhaDePagamento extends javax.swing.JFrame {

    /**
     * Creates new form FolhaDePagamento
     */
    public FolhaDePagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgColaboradores = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTXTNome = new javax.swing.JTextField();
        JTXTBeneficios = new javax.swing.JTextField();
        JTXTSalario = new javax.swing.JTextField();
        JRBEstagiario = new javax.swing.JRadioButton();
        JRBDesenvolvedor = new javax.swing.JRadioButton();
        JRBGerente = new javax.swing.JRadioButton();
        JBTCalcular = new javax.swing.JButton();
        JTXTSaida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcular Folha de Pagamento");
        setResizable(false);

        jLabel1.setText("Nome:");

        jLabel2.setText("Beneficios:");

        jLabel3.setText("Salario Bruto:");

        btgColaboradores.add(JRBEstagiario);
        JRBEstagiario.setText("Estagiario");

        btgColaboradores.add(JRBDesenvolvedor);
        JRBDesenvolvedor.setText("Desenvolvedor");

        btgColaboradores.add(JRBGerente);
        JRBGerente.setText("Gerente");

        JBTCalcular.setBackground(new java.awt.Color(255, 153, 51));
        JBTCalcular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBTCalcular.setForeground(new java.awt.Color(255, 255, 255));
        JBTCalcular.setMnemonic('C');
        JBTCalcular.setText("Calcular Salario Liquido");
        JBTCalcular.setToolTipText("Calcular Salário Líquido");
        JBTCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTCalcularActionPerformed(evt);
            }
        });

        JTXTSaida.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTXTNome)
                            .addComponent(JTXTBeneficios)
                            .addComponent(JTXTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(JRBEstagiario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JRBDesenvolvedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JRBGerente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(JBTCalcular)
                        .addGap(29, 29, 29)
                        .addComponent(JTXTSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBEstagiario)
                    .addComponent(JRBDesenvolvedor)
                    .addComponent(JRBGerente))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTXTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTXTBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTXTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBTCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(JTXTSaida))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(449, 305));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBTCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTCalcularActionPerformed
        JTXTSaida.setText("");
        Enumeration jr = btgColaboradores.getElements();
        String tipo = null;
        while (jr.hasMoreElements()) {
            JRadioButton radio = (JRadioButton) jr.nextElement();
            if (radio.isSelected()) {
                tipo = radio.getText();
            }
        }

        if (validarCampos() && tipo != null) {

            switch (tipo) {
                case "Estagiario":
                    Estagiario estagiario = new Estagiario();
                    estagiario.setBeneficios(Double.parseDouble(JTXTBeneficios.getText()));
                    estagiario.setSalarioBruto(Double.parseDouble(JTXTSalario.getText()));
                    JTXTSaida.setText("R$ " + String.valueOf(estagiario.calcularSalarioLiquido()));
                    break;
                case "Desenvolvedor":
                    Desenvolvedor desenvolvedor = new Desenvolvedor();
                    desenvolvedor.setBeneficios(Double.parseDouble(JTXTBeneficios.getText()));
                    desenvolvedor.setSalarioBruto(Double.parseDouble(JTXTSalario.getText()));
                    JTXTSaida.setText("R$ " + String.valueOf(desenvolvedor.calcularSalarioLiquido()));
                    break;
                case "Gerente":
                    Gerente gerente = new Gerente();
                    gerente.setBeneficios(Double.parseDouble(JTXTBeneficios.getText()));
                    gerente.setSalarioBruto(Double.parseDouble(JTXTSalario.getText()));
                    JTXTSaida.setText("R$ " + String.valueOf(gerente.calcularSalarioLiquido()));
                    break;
            }
        }


    }//GEN-LAST:event_JBTCalcularActionPerformed

    private boolean validarCampos() throws HeadlessException {
        if (JTXTNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira o nome", "Informação", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (JTXTBeneficios.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira o valor do benefício", "Informação", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (JTXTSalario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira o valor do salário", "Informação", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FolhaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FolhaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FolhaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FolhaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FolhaDePagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTCalcular;
    private javax.swing.JRadioButton JRBDesenvolvedor;
    private javax.swing.JRadioButton JRBEstagiario;
    private javax.swing.JRadioButton JRBGerente;
    private javax.swing.JTextField JTXTBeneficios;
    private javax.swing.JTextField JTXTNome;
    private javax.swing.JTextField JTXTSaida;
    private javax.swing.JTextField JTXTSalario;
    private javax.swing.ButtonGroup btgColaboradores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
